/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  campitos
 * Created: Nov 3, 2015
 */

CREATE TABLE CLIENTE (
ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100),EMAIL VARCHAR(100),
 PATERNO VARCHAR(100));

CREATE TABLE TARJETA1(
ID_TARJETA INTEGER PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INTEGER, 
NOMBRE_TARJETA VARCHAR(100), 
SALDO FLOAT, NUMERO_TARJETA INTEGER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));

CREATE TABLE RESERVACION(
ID_RESERVACION INTEGER PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INTEGER, ID_TARJETA INTEGER,
CIUDAD_DESTINO VARCHAR(120),
 NOMBRE_HOTEL VARCHAR(120),NUMERO_PERSONAS INTEGER,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_TARJETA) REFERENCES TARJETA1(ID_TARJETA));

SELECT * FROM RESERVACION;